name = "rhystmorgan/ccf-loans-onchain"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'rhystmorgan/ccf-loans-onchain'"

[repository]
user = "rhystmorgan"
project = "ccf-loans-onchain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fortuna"
version = "d2e5831f92b1b596bb2cc1ab801509da28650fcc"
source = "github"